#!/usr/bin/env ruby
# Encoding: utf-8
# IBM WebSphere Application Server Liberty Buildpack
# Copyright 2014 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# A simple script that checks if the runtime is available. It does this by checking if the port
# assigned to the application is accepting connections. We cannot return a return code to the user, so
# we "cheat". The user runs the script. If the script runs successfully, the caller translates this as
# returning true. If the script fails, then the user assumes the runtime is not running.

raise 'Please pass me a port' if ARGV[0].nil?
port = ARGV[0]

# Calculate the install root directory for app-management. Make no assumptions about the current working directory.
install_dir = File.expand_path('../..', File.dirname(__FILE__))
# Dynamically require the utils files.
require File.join(install_dir, '.app-management', 'utils', 'droplet_utils.rb')
port_bound = DropletUtils.port_bound?(port)
raise "Port #{port} is not in use, runtime is not running" if port_bound == false
