#!/usr/bin/env ruby
# Encoding: utf-8
# IBM WebSphere Application Server Liberty Buildpack
# Copyright 2014 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

require 'fileutils'

# directories
INSTALL_DIR = File.expand_path('../../..', File.dirname(__FILE__)).freeze
APP_MGMT_DIR = File.join(INSTALL_DIR, '.app-management').freeze

$LOAD_PATH.unshift File.expand_path(APP_MGMT_DIR, __FILE__)

require 'utils/droplet_utils'

# start-localjmx created a backup copy of the jvm.options file before modifying it. Restore the backup.
backup_file = File.join(APP_MGMT_DIR, 'backup', 'localjmx', 'jvm.options')
if File.exist?(backup_file)
  server_dir = DropletUtils.get_server_directory(INSTALL_DIR)

  # The jvm.options file in the server directory may be a sym link and not a physical file. Therefore we
  # copy file contents instead of copying the file directly.
  file_contents = File.readlines(backup_file)
  jvm_options_file = File.join(server_dir, 'jvm.options')
  jvm_options = File.new(jvm_options_file, 'w')
  jvm_options.puts(file_contents)
  jvm_options.close
  File.delete(backup_file)

  # delete the app_mgmt_localjmx.xml from configDropins
  config_file = File.join(server_dir, 'configDropins', 'defaults', 'app_mgmt_localjmx.xml')
  File.delete(config_file) if File.exist?(config_file)
end
